# Generated by Django 4.1.5 on 2023-08-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('customer', '__first__'),
        ('vehicle', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=50, unique=True, verbose_name='Medio de pago')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0.19, max_digits=10, verbose_name='I.V.A.')),
                ('tax_surcharge', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Recargo')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente')),
                ('payment_medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.paymentmedium', verbose_name='Medio de pago')),
                ('products_sell', models.ManyToManyField(to='products.sell_products', verbose_name='Productos')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='Vehículo')),
            ],
        ),
    ]
