# Generated by Django 4.1.5 on 2023-01-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('customer', '__first__'),
        ('vehicle', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Producto de factura',
                'verbose_name_plural': 'Producto de facturas',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_bill', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('city_bill', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('payments_method', models.CharField(max_length=20, verbose_name='Método de pago')),
                ('payments_medium', models.CharField(max_length=20, verbose_name='Medio de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='I.V.A.')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente')),
                ('products_bill_id', models.ManyToManyField(to='bill.bill_product', verbose_name='Productos')),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='Vehículo')),
            ],
        ),
    ]
