# Generated by Django 4.1.5 on 2023-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='products_bill_id',
            field=models.ManyToManyField(to='products.sell_products', verbose_name='Productos'),
        ),
    ]
