# Generated by Django 4.1.5 on 2023-03-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_bill_number_alter_bill_products_bill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_number',
        ),
    ]
