# Generated by Django 4.1.5 on 2023-03-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bill', '0003_remove_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number_bill',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='products_bill_id',
            field=models.ManyToManyField(to='products.products', verbose_name='Productos'),
        ),
        migrations.DeleteModel(
            name='Bill_product',
        ),
    ]
