# Generated by Django 4.1.5 on 2023-03-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bill', '0004_bill_number_bill_alter_bill_products_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='products_bill_id',
            field=models.ManyToManyField(to='products.sell_products', verbose_name='Productos'),
        ),
    ]
