# Generated by Django 4.1.5 on 2023-03-15 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_documents_number_employees_document_number'),
        ('bill', '0005_alter_bill_products_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employees', verbose_name='Vehículo'),
        ),
    ]
