# Generated by Django 4.1.5 on 2023-03-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_documents_number_employees_document_number'),
        ('bill', '0006_bill_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=20, verbose_name='Descripción')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=50, unique=True, verbose_name='Medio de pago')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, unique=True, verbose_name='Método de pago')),
            ],
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='products_bill_id',
            new_name='products_sell',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='iva',
            new_name='tax',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='city_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payments_medium',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payments_method',
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_surcharge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Recargo'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employees', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='bill',
            name='discounts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.discounts', verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.paymentmedium', verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.paymentmethod', verbose_name='Descuento'),
        ),
    ]
