# Generated by Django 4.1.5 on 2023-03-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_discounts_paymentmedium_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='monto',
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monto de descuento'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.paymentmedium', verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.paymentmethod', verbose_name='Método de pago'),
        ),
    ]
