# Generated by Django 4.1.5 on 2023-03-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_remove_discounts_monto_bill_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
