# Generated by Django 4.1.5 on 2023-03-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_remove_bill_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_time_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='number_bill',
        ),
        migrations.AlterField(
            model_name='discounts',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
    ]
