# Generated by Django 4.1.5 on 2023-03-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_remove_bill_date_time_bill_remove_bill_number_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payment_medium',
            new_name='payment_medium_id',
        ),
    ]
