# Generated by Django 4.1.5 on 2023-03-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_rename_payment_medium_bill_payment_medium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=10, verbose_name='I.V.A.'),
        ),
    ]
