# Generated by Django 4.1.5 on 2023-03-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_telephone_cel'),
        ('bill', '0012_alter_bill_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente'),
        ),
    ]
