# Generated by Django 4.1.5 on 2023-04-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_alter_bill_discounts_delete_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discounts',
        ),
    ]
