# Generated by Django 4.1.5 on 2023-08-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50, unique=True, verbose_name='Abreviatura')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('telephone_number', models.IntegerField(verbose_name='Número de telephone')),
                ('telephone_cel', models.IntegerField(null=True, verbose_name='Número de celular')),
                ('residence_address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.documenttype', verbose_name='Tipo de documento')),
            ],
        ),
    ]
