# Generated by Django 4.1.5 on 2023-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='documents_number',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='documents_type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_residence',
            new_name='residence_address',
        ),
    ]
