# Generated by Django 4.1.5 on 2023-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='Abreviatura'),
        ),
    ]
