# Generated by Django 4.1.5 on 2023-03-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_document_type_documenttype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='type',
            new_name='types',
        ),
    ]
