# Generated by Django 4.1.5 on 2023-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_type_documenttype_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telephone_cel',
            field=models.IntegerField(null=True, verbose_name='Número de celular'),
        ),
    ]
