# Generated by Django 4.1.5 on 2023-02-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('unit_value', models.IntegerField(verbose_name='Valor unitario')),
                ('totals_stock', models.IntegerField(verbose_name='Inventario total')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categories', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Buys_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buys_date', models.DateField(verbose_name='Fecha de compra')),
                ('buys_bill', models.CharField(max_length=100, unique=True, verbose_name='Factura de compra')),
                ('buys_stock', models.IntegerField(verbose_name='Cantidad de entrada')),
                ('buys_unit_value', models.IntegerField(verbose_name='Valor unitario')),
                ('total_buys_value', models.IntegerField(verbose_name='Valor total de compra')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Producto')),
            ],
        ),
    ]
