# Generated by Django 4.1.5 on 2023-02-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys_products',
            name='buys_unit_value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor unidad'),
        ),
        migrations.AlterField(
            model_name='buys_products',
            name='total_buys_value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='Sell_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(verbose_name='Fecha de venta')),
                ('sell_bill', models.CharField(max_length=100, unique=True, verbose_name='Factura de venta')),
                ('sell_stock', models.IntegerField(verbose_name='Cantidad de Salida')),
                ('sell_unit_value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor unidad')),
                ('total_sell_value', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Producto')),
            ],
        ),
    ]
