# Generated by Django 4.1.5 on 2023-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys_products',
            name='buys_bill',
            field=models.CharField(max_length=100, verbose_name='Factura de compra'),
        ),
    ]
