# Generated by Django 4.1.5 on 2023-03-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_buys_products_buys_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='sell_bill',
            field=models.CharField(max_length=100, verbose_name='Factura de venta'),
        ),
    ]
