# Generated by Django 4.1.5 on 2023-04-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_sell_products_sell_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje')),
            ],
        ),
        migrations.AddField(
            model_name='sell_products',
            name='discounts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discounts', verbose_name='Producto'),
        ),
    ]
