# Generated by Django 4.1.5 on 2023-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_discounts_sell_products_discounts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_products',
            old_name='discounts_id',
            new_name='discount_id',
        ),
        migrations.AddField(
            model_name='sell_products',
            name='discount_value',
            field=models.IntegerField(null=True, verbose_name='Descuento'),
        ),
    ]
