# Generated by Django 4.1.5 on 2023-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sell_products_discount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='discount_value',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Valor con descuento'),
        ),
    ]
