# Generated by Django 4.1.5 on 2023-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sell_products_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='buys_products',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True, verbose_name='Valor unidad'),
        ),
        migrations.AlterField(
            model_name='sell_products',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Valor con descuento'),
        ),
    ]
