# Generated by Django 4.1.5 on 2023-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_buys_products_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buys_products',
            name='percentage',
        ),
        migrations.AddField(
            model_name='products',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True, verbose_name='Valor unidad'),
        ),
    ]
