# Generated by Django 4.1.5 on 2023-04-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_buys_products_percentage_products_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True, verbose_name='Porcentaje de ganacia'),
        ),
    ]
