# Generated by Django 4.1.5 on 2023-05-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_sell_products_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tax',
            field=models.FloatField(null=True, verbose_name='I.V.A de compra'),
        ),
        migrations.AlterField(
            model_name='products',
            name='percentage',
            field=models.FloatField(null=True, verbose_name='Porcentaje de ganacia'),
        ),
    ]
