# Generated by Django 4.1.5 on 2023-05-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_tax_alter_products_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tax',
            new_name='last_tax_buy',
        ),
    ]
