# Generated by Django 4.1.5 on 2023-05-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_tax_products_last_tax_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_products',
            name='tax_sell',
            field=models.FloatField(null=True, verbose_name='Impuesto de compra'),
        ),
    ]
