# Generated by Django 4.1.5 on 2023-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_sell_products_tax_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='tax_sell',
            field=models.FloatField(default=0.19, null=True, verbose_name='Impuesto de compra'),
        ),
    ]
