# Generated by Django 4.1.5 on 2023-05-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_sell_products_tax_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='tax_sell',
            field=models.FloatField(null=True, verbose_name='I.V.A'),
        ),
    ]
