# Generated by Django 4.1.5 on 2023-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_sell_products_tax_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='buys_products',
            name='tax_buy',
            field=models.FloatField(null=True, verbose_name='I.V.A'),
        ),
    ]
