# Generated by Django 4.1.5 on 2023-02-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_names_cod', models.CharField(max_length=50, unique=True, verbose_name='Código del puesto')),
                ('jobs_names', models.CharField(max_length=100, unique=True, verbose_name='Nombre del puesto')),
            ],
            options={
                'verbose_name': 'Puesto de trabajo',
                'verbose_name_plural': 'Puestos de trabajo',
                'ordering': ['jobs_names_cod'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('documents_type', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('documents_number', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('telephone_number', models.IntegerField(verbose_name='Número de telephone')),
                ('address_residence', models.CharField(max_length=200, verbose_name='Direccion')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('salarys_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mensual')),
                ('employees_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employees_type', verbose_name='Puesto de trabajo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['names'],
            },
        ),
    ]
