# Generated by Django 4.1.5 on 2023-03-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_telephone_cel'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='documents_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.documenttype', verbose_name='Tipo de documento'),
        ),
    ]
