# Generated by Django 4.1.5 on 2023-03-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employees_documents_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='documents_number',
            new_name='document_number',
        ),
    ]
