# Generated by Django 4.1.5 on 2023-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_documents_number_employees_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='telephone_cel',
            field=models.IntegerField(null=True, verbose_name='Número de telephone'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='telephone_number',
            field=models.IntegerField(null=True, verbose_name='Número de telephone'),
        ),
    ]
