# Generated by Django 4.1.5 on 2023-03-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employees_salarys_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='documents_type',
            new_name='document_type',
        ),
    ]
