# Generated by Django 4.1.5 on 2023-03-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_rename_documents_type_employees_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employees_type_id',
            new_name='employees_type',
        ),
    ]
