# Generated by Django 4.1.5 on 2023-03-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_rename_employees_type_id_employees_employees_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='address_residence',
            new_name='residence_address',
        ),
    ]
