# Generated by Django 4.1.5 on 2023-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_address_residence_employees_residence_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='percentage',
            field=models.FloatField(null=True, verbose_name='Porcentaje'),
        ),
    ]
