# Generated by Django 4.1.5 on 2023-03-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('trademark', models.CharField(max_length=25, verbose_name='Marca')),
                ('model', models.CharField(max_length=25, verbose_name='Modelo')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categories', verbose_name='Categoría')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Propietario')),
            ],
        ),
    ]
