# Generated by Django 4.1.5 on 2023-03-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
