# Generated by Django 4.1.5 on 2023-03-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_owner_vehicle_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
